/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/layout/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    CaseCard: typeof import('./src/components/cases/CaseCard.vue')['default']
    CaseFilters: typeof import('./src/components/cases/CaseFilters.vue')['default']
    CaseStepView: typeof import('./src/components/cases/CaseStepView.vue')['default']
    EditProfileDialog: typeof import('./src/components/profile/EditProfileDialog.vue')['default']
    ProfileCard: typeof import('./src/components/profile/ProfileCard.vue')['default']
    RadialMenu: typeof import('./src/components/common/RadialMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
